// function readFromFile(name) {
//     let path = '../../src/main/resources/lyrics/processedLyrics/';
//
//     // Return the Promise generated by fetch
//     return fetch(path + name + '.json')
//         .then(response => {
//             if (!response.ok) {
//                 throw new Error(`HTTP error! Status: ${response.status}`);
//             }
//             return response.json();
//         })
//         .catch(error => {
//             console.error('Error fetching data:', error);
//             // It's important to re-throw the error here so that the caller can handle it
//             throw error;
//         });
// }